import type { ChangeEvent, RefObject } from 'react';
import { DateRangeProps, DateRangeType, FOCUS_ELEMENT, PopoverTypes } from '../types';

export type Props = {
    id: string;
    size: Required<DateRangeProps>['size'];
    variant: Required<DateRangeProps>['variant'];
    errorText?: string;
    helperText?: string;
    disabled?: boolean;
    showDecorators?: boolean;
    isActive?: boolean;
    required?: boolean;
    startDateLabel: string;
    endDateLabel: string;
    selectedDates: Required<DateRangeProps>['value'];
    showChevronIcon?: boolean;
    activePopover: PopoverTypes;
    onDateChange: Required<DateRangeProps>['onChange'];
    displayFormat: Required<DateRangeProps>['displayFormat'];
    onCalendarIconClick: (val: boolean) => void;
    setFocusedElement: (element: FOCUS_ELEMENT) => void;
    startDateRef: RefObject<HTMLInputElement>;
    endDateRef: RefObject<HTMLInputElement>;
    validator?: (val: DateRangeType, eventType: ChangeEvent<HTMLInputElement>) => string;
    showTooltipForHelperAndErrorText?: boolean;
    onCustomRangeIconClick: () => void;
    outerClickValidator: RefObject<(e: MouseEvent) => void>;
    autoComplete?: string;
};
