name: 'Chromatic'

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Linting
              run: yarn lint --since=origin/master

            - name: Build storybook
              run: yarn storybook:build

            - name: Publish to Chromatic
              run: yarn chromatic
