name: 'Chromatic'

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: yarn

            - name: Linting
              run: yarn lint

            - name: Build packages
              run: yarn build

            - name: Build storybook
              run: yarn storybook:build

            - name: Publish to Chromatic
              run: yarn chromatic
