name: 'Chromatic'

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install dependencies
              run: yarn

            - name: Linting
              run: yarn lint

            - name: Build packages
              run: yarn build

            - name: Publish to Chromatic
              if: github.ref != 'refs/heads/master'
              run: yarn chromatic

            - name: Publish to Chromatic and auto accept changes
              if: github.ref == 'refs/heads/master'
              run: yarn chromatic --auto-accept-changes
