name: Lint, Test, Build

on:
    pull_request:
        branches:
            - 'master'

jobs:
    lint-test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v3
              with:
                  main-branch-name: 'master'

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test:coverage

            - name: Build
              run: yarn build
